/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WorkSchedule;

import org.junit.jupiter.api.*;

import static org.junit.jupiter.api.Assertions.*;

class ECP1 {
    WorkSchedule schedule;

    @BeforeEach
    void setup() {
        schedule = null;
    }

    @Test
    void ECP1_1() {
        schedule = new WorkSchedule(3);
        schedule.setRequiredNumber(2, 1, 2);

        assertEquals(0, schedule.readSchedule(0).requiredNumber);
        assertEquals(2, schedule.readSchedule(1).requiredNumber);
        assertEquals(2, schedule.readSchedule(2).requiredNumber);
        assertEquals(0, schedule.readSchedule(1).workingEmployees.length);
        assertEquals(0, schedule.readSchedule(2).workingEmployees.length);
    }

    @Test
    void ECP1_1_1() {
        schedule = new WorkSchedule(3);
        schedule.setRequiredNumber(1, 2, 2);

        assertEquals(0, schedule.readSchedule(1).requiredNumber);
        assertEquals(1, schedule.readSchedule(2).requiredNumber);
    }

    @Test
    void ECP1_2() {
        schedule = new WorkSchedule(4);
        schedule.setRequiredNumber(-1, 2, 2);
        for (int i = 0; i < 4; i++) {
            assertEquals(0, schedule.readSchedule(i).requiredNumber);
        }
    }

    @Test
    void ECP1_3() {
        schedule = new WorkSchedule(5);
        //assertThrows(ArrayIndexOutOfBoundsException.class ,() -> {schedule.setRequiredNumber(0,-1,1);});
        schedule.setRequiredNumber(0, -1, 1);
        for (int i = 0; i < 5; i++) {
            assertEquals(0, schedule.readSchedule(i).requiredNumber);
        }
    }

    @Test
    void ECP1_4() {
        schedule = new WorkSchedule(2);
        schedule.setRequiredNumber(2, 1, -1);

        for (int i = 0; i < 2; i++) {
            assertEquals(0, schedule.readSchedule(i).requiredNumber);
        }
    }

    @Test
    void ECP1_5() {
        schedule = new WorkSchedule(1);
        schedule.setRequiredNumber(1, 1, 1);
        assertEquals(0, schedule.readSchedule(0).requiredNumber);
    }

    @Test
    void ECP1_6() {
        schedule = new WorkSchedule(9);

        schedule.setRequiredNumber(2, 5, 1);
        for (int i = 0; i < 9; i++) {
            assertEquals(0, schedule.readSchedule(i).requiredNumber);
        }
    }
}
